# We use the reserved private subnet 10.0.0.0/8 (::ffff:a00:0/104)
# https://en.wikipedia.org/wiki/Reserved_IP_addresses
services:
  'signal-server':
    container_name: 'signal-server' # Run only one server instance at a time
    profiles:
      - 'prod'
    build:
      context: '.'
      dockerfile: './docker/signal-server/Dockerfile'
      target: 'run'
    ports:
      - '8080:8080' # Application
      - ':8081' # Admin
    environment:
      - 'SIGNAL_SERVER_CONFIG=config/test.yml'
    secrets:
      - source: 'signal-server-secrets'
        target: '/usr/app/service/config/'
    sysctls:
      - 'net.ipv6.conf.all.disable_ipv6=0'
    networks:
      'signal-server':
  'signal-test-server':
    container_name: 'signal-server' # Run only one server instance at a time
    profiles:
      - 'staging'
    build:
      context: '.'
      dockerfile: './docker/signal-server/Dockerfile'
      target: 'run-test-server'
    ports:
      - '8080:8080' # Application
      - ':8081' # Admin
    secrets:
      - source: 'signal-server-secrets'
        target: '/usr/app/service/config/'
    networks:
      'signal-server':
  'signal-server-tests':
    container_name: 'signal-server-tests' # Run only one test instance at a time
    profiles:
      - 'dev'
    build:
      context: '.'
      dockerfile: './docker/signal-server/Dockerfile'
      target: 'integration-tests'
    networks:
      'signal-server':
secrets:
  'signal-server-secrets':
    file: './service/config/'
networks:
  'signal-server':
    driver: 'bridge'
    enable_ipv4: true
    enable_ipv6: true
    ipam:
      config:
        - subnet: '10.0.0.0/24' # 10.0.0.X
          gateway: '10.0.0.1'
