# We use the reserved private subnet 10.0.0.0/8 (::ffff:a00:0/104)
# https://en.wikipedia.org/wiki/Reserved_IP_addresses
services:
  'signal-server-production':
    container_name: 'signal-server'
    profiles:
      - 'production'
    build:
      context: '.'
      dockerfile: './docker/signal-server/Dockerfile'
      target: 'run'
    command: '-Dsecrets.bundle.filename=config/production-secrets-bundle.yml'
    environment:
      - 'REDIS_SERVER_ADDRESS=127.0.0.1'
      - 'SIGNAL_SERVER_CONFIG=config/production.yml'
    secrets:
      - source: 'signal-server-production-config'
        target: '/usr/app/service/config/production.yml'
      - source: 'signal-server-production-bundle'
        target: '/usr/app/config/production-secrets-bundle.yml'
    networks:
      'signal-server':
  'signal-server-testing':
    profiles:
      - 'testing'
    build:
      context: '.'
      dockerfile: './docker/signal-server/Dockerfile'
      target: 'test'
    command: '-Dsecrets.bundle.filename=config/test-secrets-bundle.yml'
    environment:
      - 'REDIS_SERVER_ADDRESS=127.0.0.1'
      - 'SIGNAL_SERVER_CONFIG=config/test.yml'
    secrets:
      - source: 'signal-server-testing-config'
        target: '/usr/app/service/config/test.yml'
      - source: 'signal-server-testing-bundle'
        target: '/usr/app/config/test-secrets-bundle.yml'
    networks:
      'signal-server':
secrets:
  'signal-server-production-config':
    file: './service/config/production.yml'
  'signal-server-production-bundle':
    file: './config/production-secrets-bundle.yml'
  'signal-server-testing-config':
    file: './service/config/test.yml'
  'signal-server-testing-bundle':
    file: './config/test-secrets-bundle.yml'
networks:
  'signal-server':
    driver: 'bridge'
    enable_ipv4: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: '10.0.0.0/24' # ::ffff:a00:0/120
          gateway: '10.0.0.1' # ::ffff:a00:1
